config {
    schema: "staging",
    description: "WHAT: Provides raw hit level data export from Google Analytics (Universal Analytics). Each row represents a record for every digital session and each hit level event lives within the hits struct. Data is loaded from a native Google integration between GA and BigQuery. Information on this GA export is available here: https://support.google.com/analytics/answer/3437719?hl=en . Partitioned by session_start_date_pt and clustered by data_source and unique_session_id. \r\nWHEN: Data is available for all digital events dating back to FY2020. \r\nWHO: eCommerce \r\nWHY: Provides the ability to analyze each session and event that is tracked on A.com.",
    type: "view"
}

SELECT
  ${explicit_field_selection.ga_sessions('ga_sessions')}
FROM
  ${ref("ga_sessions_*")}
WHERE
  _table_suffix >= FORMAT_DATE('%Y%m%d',${constants.first_date_to_load_data})
  --convert to YYYYMMDD
  AND _table_suffix < FORMAT_DATE('%Y%m%d',${constants.ga4_cutover_date})
  --convert to YYYYMMDD
  AND totals.visits IS NOT NULL
  --removing non-interacting sessions as they will show as null. Done to align with GA UI.
  AND EXISTS (
  SELECT
    1
  FROM
    UNNEST(hits) AS hits
  WHERE
    hits.page.hostname = 'www.aritzia.com')
    --remove other hostname sessions from dev environments and archivesale.aritzia.com
  /* if dev or feature branch, use limited TY and LY dates to reduce data processed while still allowing YoY comp testing */
  ${typeof dataform.projectConfig.vars.envName === 'undefined' || dataform.projectConfig.vars.envName === 'dev' ? "and ( _table_suffix >= format_date('%Y%m%d', date_sub(current_date(), interval 3 week)) or _table_suffix between format_date('%Y%m%d', date_sub(current_date(), interval 55 week)) and format_date('%Y%m%d',date_sub(current_date(), interval 1 year)))" : ""}
