config {
    schema: "staging",
    description: "Provides raw hit level data export from Google Analytics 4. Each row represents a single event that occurred on A.com. Data is loaded from a native Google integration between GA4 and BigQuery. Information on this GA export is available here: https://support.google.com/analytics/answer/7029846?hl=en ",
    type: "incremental",
    bigquery: {
        partitionBy: "event_date",
        clusterBy: ["ga_session_key", "event_name"]
    }
}

WITH
  unnested_events AS (
  SELECT
    TIMESTAMP_MICROS(event_timestamp) AS hit_started_at,
    -- this bundles some events into same timestamp. need to create your own hit timestamp event parameter to get around this?
    CAST(RIGHT(_table_suffix, 8) AS date format 'YYYYMMDD') AS event_date,
    event_name,
    user_pseudo_id,
    CONCAT(user_pseudo_id, ".",(
      SELECT
        value.int_value
      FROM
        UNNEST(event_params)
      WHERE
        KEY = 'ga_session_id')) AS ga_session_key,
    ${helpers.getEventParam('entrances', 'int')},
    ${helpers.getEventParam('ga_session_id', 'int', 'session_start')},
    --ga session id is in unix number timestamp
    ${helpers.getEventParam('page_referrer')},
    ${helpers.getEventParam('page_title')},
    ${helpers.getEventParam('page_location')},
    ${helpers.getEventParam('view_port')},
    ${helpers.getEventParam('user_agent_string')},
    device.web_info.hostname AS host_name,
    CONCAT('/', REGEXP_REPLACE( (
        SELECT
          p.value.string_value
        FROM
          UNNEST(event_params) AS p
        WHERE
          p.key = 'page_location' ), r'^https?://[^/]+|[\?#].*|/en/|en/|/fr/|/us/|/intl/|.html|/default|en_CA', ''
          -- clean up page_location to remove https://,intl/us/en etc.
          )) AS page_path,
      IF
        (event_name = 'first_visit', 1,0) AS is_first_visit,
        --general session attributes
        ${helpers.getUserProperty('logged_in')},
        ${helpers.getEventParam('ga_session_number', 'int')},
        ${helpers.getEventParam('session_engaged', 'int')},
        --traffic source
        collected_traffic_source.manual_medium AS traffic_source_medium,
        collected_traffic_source.manual_source AS traffic_source_source,
        collected_traffic_source.manual_content AS traffic_source_ad_content,
        collected_traffic_source.manual_term AS traffic_source_keyword,
        collected_traffic_source.manual_campaign_name AS traffic_source_campaign,
        collected_traffic_source.manual_campaign_id AS traffic_source_campaign_id,
        --device
        device.category AS device_category,
        device.mobile_brand_name AS device_mobile_brand_name,
        device.mobile_model_name AS device_mobile_model_name,
        device.operating_system_version AS device_operating_system_version,
        device.web_info.hostname AS device_web_info_hostname,
        device.web_info.browser AS device_web_info_browser,
        CAST(NULL AS string) AS device_screen_resolution,
        --geo
        geo.country AS geo_country,
        geo.region AS geo_region,
        geo.metro AS geo_metro,
        geo.city AS geo_city,
      FROM
        ${ref("events_*")}
      WHERE
        -- to account for 30 day session traffic source attribution lookback window
        _table_suffix NOT LIKE "%intraday%"
        AND _table_suffix NOT LIKE "%fresh%"
        AND CAST(RIGHT(_table_suffix, 8) AS date format 'YYYYMMDD') >= event_date_checkpoint )
        -- final select
  SELECT
    CURRENT_TIMESTAMP() AS row_loaded_at,
    event_date,
    ga_session_key,
    user_pseudo_id,
    session_start,
    event_name,
    hit_started_at,
    STRUCT( page_path,
      host_name,
      page_title,
      page_location ) AS page,
  IF
    (event_name = 'first_visit', 1,0) AS is_first_visit,
    logged_in,
    ga_session_number,
    session_engaged,
    --traffic source
    CASE
      WHEN REGEXP_CONTAINS(page_location, r'gclid=.+') AND traffic_source_source = 'google' THEN 'cpc'
      /* Known GA4 misattribution bug */
      ELSE traffic_source_medium
  END
    AS traffic_source_medium,
    traffic_source_source,
    traffic_source_ad_content,
    traffic_source_keyword,
    traffic_source_campaign,
    traffic_source_campaign_id,
    --device
    device_category,
    device_mobile_brand_name,
    device_mobile_model_name,
    device_operating_system_version,
    device_web_info_browser,
    device_screen_resolution,
    --geo
    geo_country,
    geo_region,
    geo_metro,
    geo_city
  FROM
    unnested_events

pre_operations {
  DECLARE
    event_date_checkpoint DEFAULT (
    ${
        when(incremental(),
            `select max(event_date) -3 from ${self()}`,
            `select (${constants.ga4_cutover_date})-30` //go back further than first GA4 date due to 30 day window for last non direct attribution
        )
    }
    );
    ${
        when(incremental(),
            `delete from ${self()} where event_date >= event_date_checkpoint`
        )
    }
}
