config {
    schema: "intermediate",
    type: "incremental",
    bigquery: {
        partitionBy: "session_date",
        clusterBy: ["ga_session_key"]
    }
}

  /* Special care must be made to ensure the schemas align exactly between the two datasets */
SELECT
  row_loaded_at,
  ga_session_key,
  session_date,
  STRUCT(session.user_pseudo_id,
    session.session_number,
    session.session_start_time_pt,
    session.session_type,
    last_non_direct_traffic_source,
    device,
    location,
    total ) AS session
FROM
  ${ref("int_ga3_sessions")}
WHERE
  session_date < ${constants.ga4_cutover_date}
  ${
      when(incremental(),
          `and 1=0`
      )
  }
UNION ALL
SELECT
  row_loaded_at,
  ga_session_key,
  session_date,
  STRUCT(session.user_pseudo_id,
    session.session_number,
    session.session_start_time_pt,
    session.session_type,
    last_non_direct_traffic_source,
    device,
    location,
    total) AS session
FROM
  ${ref("int_ga4_sessions")}
WHERE
  session_date >= ${constants.ga4_cutover_date}
  ${
      when(incremental(),
          `and session_date >= session_date_checkpoint`
      )
  }

pre_operations {
  DECLARE
    session_date_checkpoint DEFAULT (
    ${
        when(incremental(),
            `select max(session_date) -3 from ${self()}`,
            `select date("2000-01-01")`)
    }
    );
    ${
        when(incremental(),
            `delete from ${self()} where session_date >= sesion_date_checkpoint`)
    }
}
