config {
    schema: "intermediate",
    description: "",
    type: "incremental",
    bigquery: {
        partitionBy: "session_date"
    }
}

  -- Group distinct attributes by session (ordered by hit_started_at)
WITH
  distinct_session_attributes AS (
  SELECT
    DISTINCT ga_session_key,
    user_pseudo_id,
    event_date AS session_date,
    FIRST_VALUE(hit_started_at) OVER (session_window) AS session_start_timestamp,
    LAST_VALUE(logged_in IGNORE NULLS) OVER (session_window) AS session_login_status,
    MAX(session_engaged) OVER (session_window) AS session_engaged,
    MAX(is_first_visit) OVER (session_window) AS session_type,
    MIN(ga_session_number) OVER (session_window) AS session_number,
    --device
    LAST_VALUE(device_category IGNORE NULLS) OVER (session_window) AS device_category,
    LAST_VALUE(device_operating_system_version IGNORE NULLS) OVER (session_window) AS device_operating_system_version,
    LAST_VALUE(device_mobile_brand_name IGNORE NULLS) OVER (session_window) AS device_mobile_brand_name,
    LAST_VALUE(device_mobile_model_name IGNORE NULLS) OVER (session_window) AS device_mobile_model_name,
    LAST_VALUE(device_web_info_browser IGNORE NULLS) OVER (session_window) AS device_browser,
    --geo
    LAST_VALUE(geo_country IGNORE NULLS) OVER (session_window) AS geo_country,
    LAST_VALUE(geo_region IGNORE NULLS) OVER (session_window) AS geo_state_name,
    LAST_VALUE(geo_city IGNORE NULLS) OVER (session_window) AS geo_city_name,
    LAST_VALUE(geo_metro IGNORE NULLS) OVER (session_window) AS geo_metro_name
  FROM
    ${ref("stg_ga4_events")}
    -- staged_ecommerce.digital_events_ga4 contains data from 30 days prior to GA4 cutover date so this filter is needed
  WHERE
    event_date >= ${constants.ga4_cutover_date}
    ${
        when(incremental(),
            `and event_date >= session_date_checkpoint`
        )
    }
  WINDOW
    session_window AS (
    PARTITION BY
      ga_session_key
    ORDER BY
      hit_started_at ROWS BETWEEN UNBOUNDED PRECEDING
      AND UNBOUNDED FOLLOWING) )
      -- final select to bring in struct format
SELECT
  CURRENT_TIMESTAMP() AS row_loaded_at,
  SHA256(distinct_session_attributes.ga_session_key || event_date ) AS row_id,
  distinct_session_attributes.session_date,
  distinct_session_attributes.ga_session_key,
  'ga4_events' as data_source,
  STRUCT( distinct_session_attributes.user_pseudo_id,
  session_number,
  session_login_status,
  --truncating to second granularity to match GA UA
  DATETIME_TRUNC(DATETIME(session_start_timestamp, "America/Vancouver"), second) AS session_start_time_pt,
  CASE
    WHEN session_type = 1 THEN 'New Visit'
    ELSE 'Returning Visit'
END
  AS session_type,
  CASE
    WHEN session_engaged = 1 THEN TRUE
    ELSE FALSE
END
  AS is_engaged_session,
  STRUCT( last_non_direct.traffic_source_ad_content AS ad_content,
    last_non_direct.traffic_source_campaign AS campaign,
    last_non_direct.traffic_source_campaign_id AS campaign_id,
    last_non_direct.traffic_source_keyword AS keyword,
    last_non_direct.traffic_source_medium AS medium,
    last_non_direct.traffic_source_source AS SOURCE,
    CASE
    -- Cross-network: Campaign Name contains "cross-network"
      WHEN REGEXP_CONTAINS(last_non_direct.traffic_source_campaign, r"cross-network") THEN 'Paid Search'
      -- Paid Shopping:
      --   (Source matches a list of shopping sites
      --   OR
      --   Campaign Name matches regex ^(.*(([^a-df-z]|^)shop|shopping).*)$)
      --   AND
      --   Medium matches regex ^(.*cp.*|ppc|retargeting|paid.*)$
      WHEN ( ga4_source_categories.source_category = 'SOURCE_CATEGORY_SHOPPING'
      OR REGEXP_CONTAINS(last_non_direct.traffic_source_campaign, r"^(.*(([^a-df-z]|^)shop|shopping).*)$") )
    AND REGEXP_CONTAINS(last_non_direct.traffic_source_medium,r"^(.*cp.*|ppc|retargeting|paid.*)$") THEN 'Paid Search'
    -- Paid Search:
    --   Source matches a list of search sites
    --   AND
    --   Medium matches regex ^(.*cp.*|ppc|retargeting|paid.*)$
      WHEN ga4_source_categories.source_category = 'SOURCE_CATEGORY_SEARCH' AND REGEXP_CONTAINS(last_non_direct.traffic_source_medium, r"^(.*cp.*|ppc|retargeting|paid.*)$") THEN 'Paid Search'
      -- Paid Social:
      --   Source matches a regex list of social sites
      --   AND
      --   Medium matches regex ^(.*cp.*|ppc|retargeting|paid.*)$
      WHEN ga4_source_categories.source_category = 'SOURCE_CATEGORY_SOCIAL'
    AND REGEXP_CONTAINS(last_non_direct.traffic_source_medium, r"^(.*cp.*|ppc|retargeting|paid.*)$") THEN 'Paid Social'
    -- Display:
    --   Medium is one of ("display", "banner", "expandable", "interstitial", "cpm")
      WHEN last_non_direct.traffic_source_medium IN ('display', 'banner', 'expandable', 'interstitial', 'cpm') THEN 'Display'
      -- Email:
      --   Source = email|e-mail|e_mail|e mail
      --   OR
      --   Medium = email|e-mail|e_mail|e mail
      WHEN REGEXP_CONTAINS(last_non_direct.traffic_source_source, r"email|e-mail|e_mail|e mail")
    OR REGEXP_CONTAINS(last_non_direct.traffic_source_medium, r"email|e-mail|e_mail|e mail") THEN 'Email'
    -- Organic Search:
    --   Source matches a list of search sites
    --   OR
    --   Medium exactly matches organic
      WHEN ga4_source_categories.source_category = 'SOURCE_CATEGORY_SEARCH' OR last_non_direct.traffic_source_medium = 'organic' THEN 'Organic Search'
      -- Organic Shopping: Map to GA3's Social Category
      --   Source matches a list of shopping sites
      --   OR
      --   Campaign name matches regex ^(.*(([^a-df-z]|^)shop|shopping).*)$
      WHEN ga4_source_categories.source_category = 'SOURCE_CATEGORY_SHOPPING'
    OR REGEXP_CONTAINS(last_non_direct.traffic_source_campaign, r"^(.*(([^a-df-z]|^)shop|shopping).*)$") THEN 'Organic Search'
    -- Organic Social:
    --   Source matches a regex list of social sites or video sites
    --   OR
    --   Medium is one of ("social", "social-network", "social-media", "sm", "social network", "social media")
      WHEN ga4_source_categories.source_category IN ('SOURCE_CATEGORY_SOCIAL', 'SOURCE_CATEGORY_VIDEO') OR last_non_direct.traffic_source_medium IN ("Social", "social", "social-network", "social-media", "sm", "social network", "social media") OR REGEXP_CONTAINS(last_non_direct.traffic_source_medium, r"^(.*video.*)$") THEN 'Social'
      -- Affiliates:
      --   Medium = affiliate
      WHEN last_non_direct.traffic_source_medium = 'affiliate' THEN 'Affiliates'
      -- Audio:
      --   Medium exactly matches audio
      WHEN last_non_direct.traffic_source_medium = 'audio' THEN 'Audio'
      -- SMS:
      --   Source exactly matches sms
      --   OR
      --   Medium exactly matches sms
      WHEN last_non_direct.traffic_source_source = 'sms'
    OR last_non_direct.traffic_source_medium = 'sms' THEN 'SMS'
    -- Mobile Push Notifications:
    --   Medium ends with "push"
    --   OR
    --   Medium contains "mobile" or "notification"
    --   OR
    --   Source exactly matches "firebase"
      WHEN REGEXP_CONTAINS(last_non_direct.traffic_source_medium, r"push$") OR REGEXP_CONTAINS(last_non_direct.traffic_source_medium, r"mobile|notification") OR last_non_direct.traffic_source_source = 'firebase' THEN 'Mobile Push Notifications'
      -- Referral:
      --   Medium is one of ("referral", "app", or "link")
      WHEN last_non_direct.traffic_source_medium IN ("referral",
      "app",
      "link") THEN 'Referral'
      -- Direct: Source exactly matches "(direct)" AND Medium is one of ("(not set)", "(none)")
      WHEN ( last_non_direct.traffic_source_source IS NULL AND last_non_direct.traffic_source_medium IS NULL ) OR ( last_non_direct.traffic_source_source = '(direct)' AND (last_non_direct.traffic_source_medium = '(none)' OR last_non_direct.traffic_source_medium = '(not set)') ) THEN 'Direct'
      -- Unassigned/(Other) is the value Analytics uses when there are no other channel rules that match the event data.
      ELSE '(Other)'
  END
    AS traffic_channel ) AS traffic_source,
  STRUCT( device_category,
    CONCAT(device_mobile_brand_name, ' ', device_mobile_model_name) AS mobile_device_info,
    device_operating_system_version AS operating_system_version,
    CAST(NULL AS string) AS screen_resolution,
    /* not available in the BigQuery export 20240320 */
    device_browser AS browser ) AS device,
  STRUCT( geo_country AS country_name
  --geo_state_name AS province_state_name,
  -- geo_city_name AS city_name
  ) AS location ) AS digital_session
  FROM
    distinct_session_attributes
  LEFT OUTER JOIN
    ${ref("int_ga4_last_non_direct_attribution")} AS traffic_source
  ON
    traffic_source.ga_session_key = distinct_session_attributes.ga_session_key
    AND traffic_source.event_date = distinct_session_attributes.session_date
  LEFT OUTER JOIN
    ${ref("stg_ga4_source_categories")} AS ga4_source_categories
  ON
    ga4_source_categories.source = traffic_source.last_non_direct.traffic_source_source
  WHERE
    distinct_session_attributes.ga_session_key IS NOT NULL
    AND distinct_session_attributes.user_pseudo_id IS NOT NULL

pre_operations {
  DECLARE
    session_date_checkpoint DEFAULT (
    ${
        when(incremental(),
            `select max(session_date) -3 from ${self()}`,
            `select (${constants.ga4_cutover_date})`
        )
    }
    );
    ${
        when(incremental(),
            `delete from ${self()} where session_date >= session_date_checkpoint`
        )
    }
}
