config {
    schema: "modeled_ecommerce",
    type: "incremental",
    bigquery: {
        partitionBy: "event_date",
        clusterBy: ["ga_session_key"],
    }
}

SELECT
  CURRENT_TIMESTAMP() AS row_loaded_at,
  data_source,
  event_date,
  ga_session_key,
  STRUCT( event_name,
    ROW_NUMBER() OVER (PARTITION BY ga_session_key ORDER BY hit_started_at ASC ) AS hit_number,
  IF
    (event_name = 'page_view', 'page', 'event') AS hit_type,
  IF
    (CASE
        WHEN event_name = 'page_view' THEN ROW_NUMBER() OVER (PARTITION BY ga_session_key, event_name ORDER BY hit_started_at ASC)
        ELSE NULL
    END
      = 1, TRUE, FALSE) AS is_entrance,
  IF
    (CASE
        WHEN event_name = 'page_view' THEN ROW_NUMBER() OVER (PARTITION BY ga_session_key, event_name ORDER BY hit_started_at DESC)
        ELSE NULL
    END
      = 1, TRUE, FALSE) AS is_exit,
    CAST(NULL AS int) AS hit_time_from_session_start,
    hit_started_at,
    page,
    transaction_id,
  IF
    (event_name = 'contact_us', TRUE, FALSE) AS is_contact_us_event,
  IF
    (event_name = 'select_item', TRUE, FALSE) AS is_product_click_event,
  IF
    (event_name = 'view_promotion', TRUE, FALSE) AS is_promotion_seen_event,
  IF
    (event_name = 'select_promotion', TRUE, FALSE) AS is_promotion_click_event,
  IF
    (event_name = 'filter', TRUE, FALSE) AS is_filter_applied_event,
  IF
    (event_name = 'add_to_cart',TRUE, FALSE) AS is_add_to_bag_event,
  IF
    (event_name = 'remove_from_cart',TRUE,FALSE) AS is_remove_from_bag_event,
  IF
    (event_name = 'view_wishlist', TRUE, FALSE) AS is_mylist_seen_event,
  IF
    (event_name = 'account_created', TRUE, FALSE) AS is_account_creation_completed_event,
  IF
    (event_name = 'begin_checkout', TRUE, FALSE) AS is_begin_checkout_event,
  IF
    (event_name = 'site_error', TRUE, FALSE) AS is_site_error_event ) AS hit
FROM
  ${ref("stg_ga4_events")}
WHERE
  ga_session_key IS NOT NULL
  -- dependency datasets contain 30 days prior to GA4 cutover date so this filter is needed
  AND session_start_date_pt >= ${constants.ga4_cutover_date}
  ${
      when(incremental(),
          `and event_date >= event_date_checkpoint`
      )
  }

pre_operations {
  DECLARE
    event_date_checkpoint DEFAULT (
    ${
        when(incremental(),
            `select max(event_date) -3 from ${self()}`,
            `select date("2000-01-01")`
        )
    }
    );
    ${
        when(incremental(),
            `delete from ${self()} where event_date >= event_date_checkpoint`
        )
    }
}
